spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/mytest?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计 'wall'用于防火墙
      filters: stat,wall,log4j2
      filter:
        config:
          enabled: false
        stat:
          enabled: true
          db-type: mysql
        wall:
          enabled: true
        log4j2:
          enabled: true
          statement-executable-sql-log-enable: true
      stat-view-servlet:
        #默认值为true，即打开监控页面，但存在泄漏信息的风险，所以修改为false
        enabled: true
        #配置监控页面登录用户名，启用监控页面后才可用
        login-username: admin
        #配置监控页面登录密码，启用监控页面后才可用
        login-password: 123456
        #配置允许访问监控页面的IP地址
        allow: 127.0.0.1
      web-stat-filter:
        #默认值为true，统计web关联的监控信息如session/url等，建议修改为false
        enabled: false
        #该功能模块代码不完善，特定场景下会诱发异常，非特别需求，建议修改为false
        session-stat-enable: false
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 300
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 0
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  quartz:
    job-store-type: jdbc
  devtools:
    livereload:
      enabled: false

server:
  port: 8081
  tomcat:
    max-threads: 30000
    accept-count: 60000
  servlet:
    context-path: /javaee

mybatis-plus:
  mapper-locations: classpath:xml/*.xml
